### ISSUE TITLE
When trying to load Chainlink front end, "waiting for http://localhost:6991" suspends

### ISSUE THREAD

**Issue by TheGreatAlgo** [smartcontractkit/chainlink-polkadot#37] opened 2020-09-18 12:42 UTC
I am running the ./setup command but it keeps suspending while waiting for localhost:6691.

I can access the substrate-front-end-template. Just not chainlink.

It errors out on an error:

"Timed out waiting for 'curl -s "http://localhost:6691/"' (waited 60s)."

Any ideas why?

![image](https://user-images.githubusercontent.com/37487508/93598562-db673a80-f98a-11ea-92aa-72be13cbb61d.png)

**Comment by LaurentTrk** [comment] 2020-09-18 13:51
Hi @TheGreatAlgo ,
Did you look at [this issue](https://github.com/smartcontractkit/chainlink-polkadot/issues/36#issuecomment-694701872) and it's workaround ?
Check the `docker ps` command to see if your container are started (should not be the case...)

**Comment by TheGreatAlgo** [comment] 2020-09-18 14:10
@LaurentTrk using my infura key did the trick.

**Comment by krebernisak** [comment] 2020-09-22 09:13
Closing as this is now fixed with the new Chainlink 0.8.16 release. Also, duplicate of [issue #36](https://github.com/smartcontractkit/chainlink-polkadot/issues/36).

**Closed by krebernisak** 2020-09-22 09:13 UTC
Labels: bug
